### ISSUE TITLE
Better support non-bash shells

### ISSUE THREAD

**Issue by androidacy-user** [Bashfuscator/Bashfuscator#29]
I'm developing a script for use in an environment where it will be ran under busybox ash.

Using this obfuscator seems is causing syntax errors.

Is there any existing way to get obfuscated scripts to run under ash, or is there no way currently to do this?

**Comment by Church13** [comment]
If you'd like the script will be compatible with ash, you'd have to modify the core way that Bashfuscator works -- it's not meant to be compatible with anything but bash, hence the name. The obfuscation methods make use of quirks and functionality of bash. Syntax errors are occurring because you can't run bash scripts using ash. The obfuscated scripts generated by Bashfuscator are still for Bash. Either don't use busybox, or use a different image that has bash if you'd like to use Bashfuscator.

This isn't really an issue -- it's essentially a feature request to support other shells, which isn't the purpose of this project.
